function SX29 = import_phn_table(filename)

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/sky/Documents/MATLAB/Speech_signal_processing/Final_project/SX29.PHN
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/12/01 15:40:53

%% Initialize variables.
% filename = '/home/sky/Documents/MATLAB/Speech_signal_processing/Final_project/SX29.PHN';
delimiter = ' ';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: categorical (%C)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
SX29 = table(dataArray{1:end-1}, 'VariableNames', {'VarName1','VarName2','h'});

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

end 